version: "3.8"
services:
  backend:
    container_name : backend
    build: ./backend
    env_file: 
    - ./backend/.env
    ports: 
    - "3000:3000"


  fronted:
      container_name: frontend
      build: ./frontend
      env_file: 
      - ./frontend
      ports:
      - "5173:5173"

